services:
  postgres:
    image: postgres:18
    container_name: smart_gym_db
    volumes:
      - postgresql-data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: UPAQi4M24FwfYEUqbY0m
      POSTGRES_DB: smart_gym_db
    ports:
      - "5432:5432"


  backend:
    build: ./backend
    container_name: smart_gym_api
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/smart_gym_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=UPAQi4M24FwfYEUqbY0m
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgres


volumes:
  postgresql-data: