spring.application.name=Smart Gym API

spring.datasource.url=jdbc:postgresql://localhost:5432/smart_gym_db?sslmode=disable
spring.datasource.username=postgres
spring.datasource.password=UPAQi4M24FwfYEUqbY0m
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.jpa.show-sql=true

application.security.jwt.secret-key=9exNUQ2fGNqKFEjPZHvVkqFk7q3AeVbimDsixxWv8pkFBZzG
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000